name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: deploy on master
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: NodeJS Action Template
      uses: bitoiu/node-js-action-template@v1.0
    - name: npm install
      run: npm start
      env:
        CI: true
